[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
ir = {path="../ir/"}
value = {path = "../value/"}

[dev-dependencies]
frontend= {path="../frontend/"}
rstest = "0.22.0"
ffi= {path = "../ffi/"}
