PostCondition = {":"~Exp}

Brake = { (^"B"|^"Break")~PostCondition?~("  " | " "~Exp~(","~Exp)*)}
Close = { (^"C"|^"close")~PostCondition?~(" "~Exp~(","~Exp)*)}
Else = { (^"e"|^"else")~"  "}

DoArg = {ExtrinsicFunction~PostCondition?}
Do = { (^"D"|^"Do")~PostCondition?~("  " | " "~DoArg~(","~DoArg)*)}

ForArg = {Exp~(":"~Exp){,2} }
For = { (^"F"|^"for")~" "~(Variable~"="~(ForArg ~(","~ForArg)*))?~" "~Commands}
Commands = { (Brake | Close | Do | Else | For)* }
Line = { Commands }