String = { quote ~( !quote~ANY | quote~quote)* ~quote}

//Currently . is a valid number (==0) Mabey fix this.
Number = { ("+" | "-")* ~ &(ASCII_DIGIT | "." ) ~(ASCII_DIGIT* ~ "."? ~ ASCII_DIGIT*)}

//TODO once I have everything in Rust this will need to be restrucutred to handle recurstion. 
Atom = {  Variable | UnaryOperator | String | Number |   "("~Exp~")" }

PatternOpCode = _{ OPPAT | OPNPAT }

Exp = { Atom ~ (PatternOpCode~Pattern | !PatternOpCode ~ BinaryOperator ~Atom)*}

Eval = {Exp}