[package]
name = "lang-model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-mumps = { path = "../tree-sitter-M"}
tree-sitter = "0.20.10"
