name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v4
      with:
       path: |
         ~/.cargo
         ./target/
       key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v4
    - name: install tree-sitter
      run: cargo install tree-sitter-cli --version 0.22.6  --locked
    - name: dbg
      run: ls ./
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
